## Please do not touch this location 
s3_bucket       = "czr-platform-usw2-tf-state"
account         = "046638516000"
environment     = "qa"
s3_region       = "us-west-2"
s3_folder       = "share_tools"
s3_folder_type  = "iam"
s3_tfstate_file = "raas_iam.tfstate"
## Please do not touch above code 
region          = "us-west-2"

##roles and policies
existing_eks_cluster_role   = "czr-qa-usw2-iam-eks-cluster-nodegroup-role"
eks_cluster_policy          = "czr-raas-policy-qa-eks-cluster-secret-manager"

##Secrets Information
jwt_secret              = "czr-raas-secret-usw2-qa-jwt-keys-O7taIa"
database_secret         = "czr-raas-secret-usw2-qa-db-config-S9M1Ya"
database_secret_raas_offers = "czr-raas-offers-secret-usw2-qa-db-config-A4x0Ny"
strikeiron_secret       = "czr-raas-secret-usw2-qa-strikeiron-config-39Gfvb"
em1_secret              = "czr-raas-secret-usw2-qa-eml-keys-O7taIa"
gms_secret              = "czr-raas-secret-usw2-qa-gms-key-uiWVGC"
gms_guest_secret        = "czr-raas-secret-usw2-qa-gms-create-guest-key-oXJoXr"
pdb_republish_secret    = "czr-raas-secret-usw2-qa-pdb-republish-8bZ5Mc"
kafka_secret            = "czr-raas-secret-usw2-qa-kafka-config-39Gfvb"
security_questions_limit= "czr-raas-secret-usw2-qa-security-questions-limit-8bZ5Mc"
lambda_enc_secret       = "czr-raas-secret-usw2-qa-aws-lambda-enc-secret-39Gfvb"
gms_get_rg_secret       = "czr-raas-secret-usw2-qa-sms-service-config-s2aMRe"
sms_secret              = "czr-raas-secret-usw2-qa-gms-get-rg-info-5Fyi9c"
error_logger_secret     = "czr-raas-secret-usw2-qa-caesars-error-logger-JOmtfL"
tenable_audit           = "/svc/credentials/tenable-audit-w0ycCo"
crypto_Secret           = "cryptoSecret-zVJX6P"
jwt_config              = "jwt_config-6a5Yjy"
ENC_KEY                 = "ENC_KEY-SXaSHg"
GMS_KEYS                = "GMS_KEYS-WiVQkl"
STRIKEIRON_CREDENTIAL   = "STRIKEIRON_CREDENTIAL-yjebZe"
iden_encrypt_secret     = "czr-raas-secret-usw2-qa-iden-encrypt-secret-diDC73"
role_name_flowlog       = "czr-raas-role-qa-flowlog"
policy_name_flowlog     = "czr-raas-policy-qa-flowlog"
oauthtoken              = "czr-raas-secret-usw2-qa-gms-validate-oauthtoken-key-uklopX"
leap_auth_provider_keys = "czr-raas-secret-usw2-qa-leap-auth-provider-keys-Qb3OGH"
sa_get_rg_secret        = "czr-raas-secret-usw2-qa-sa-get-rg-info-I9Vn7j"