## Please do not touch this location 
s3_bucket       = "czr-platform-usw2-tf-state"
account         = "121054486353"
environment     = "prod"
s3_region       = "us-west-2"
s3_folder       = "share_tools"
s3_folder_type  = "iam"
s3_tfstate_file = "raas_iam.tfstate"
## Please do not touch above code 
region          = "us-west-2"

##roles and policies
existing_eks_cluster_role   = "czr-prod-usw2-raas-eksclusters-node-role"
eks_cluster_policy          = "czr-raas-policy-prod-eks-cluster-secret-manager"

##Secrets Information
jwt_secret              = "czr-raas-secret-usw2-prod-jwt-keys-cikrTP"
database_secret         = "czr-raas-secret-usw2-prod-db-config-YZtxSF"
database_secret_raas_offers = "czr-raas-offers-secret-usw2-prod-db-config-RfDFGv"
strikeiron_secret       = "czr-raas-secret-usw2-prod-strikeiron-config-uwodPr"
em1_secret              = "czr-raas-secret-usw2-prod-eml-keys-HPf7QB"
gms_secret              = "czr-raas-secret-usw2-prod-gms-key-ocnhxg"
gms_guest_secret        = "czr-raas-secret-usw2-prod-gms-create-guest-key-RwhHVr"
pdb_republish_secret    = "czr-raas-secret-usw2-prod-pdb-republish-mAKRyu"
kafka_secret            = "czr-raas-secret-usw2-prod-kafka-config-Bu2A8q"
security_questions_limit= "czr-raas-secret-usw2-prod-security-questions-limit-79VCjf"
lambda_enc_secret       = "czr-raas-secret-usw2-prod-aws-lambda-enc-secret-VuH9hW"
gms_get_rg_secret       = "czr-raas-secret-usw2-prod-gms-get-rg-info-y7fxLK"
sms_secret              = "czr-raas-secret-usw2-prod-sms-service-config-D9yo2K"
tenable_audit           = "/svc/credentials/tenable-audit-xE7zWl"
error_logger_secret     = "czr-raas-secret-usw2-prod-caesars-error-logger-vfkSHn"                     
crypto_Secret           = "cryptoSecret-zVJX6P"
jwt_config              = "jwt_config-6a5Yjy"
ENC_KEY                 = "ENC_KEY-SXaSHg"
GMS_KEYS                = "GMS_KEYS-WiVQkl"
STRIKEIRON_CREDENTIAL   = "STRIKEIRON_CREDENTIAL-yjebZe"
iden_encrypt_secret     = "czr-raas-secret-usw2-prod-iden-encrypt-secret-AcJAAO"
role_name_flowlog       = "czr-raas-role-prod-flowlog"
policy_name_flowlog     = "czr-raas-policy-prod-flowlog"
oauthtoken              = "czr-raas-secret-usw2-prod-gms-validate-oauthtoken-key-upR7N6"
leap_auth_provider_keys = "czr-raas-secret-usw2-prod-leap-auth-provider-keys-qJV9bn"
sa_get_rg_secret        = "czr-raas-secret-usw2-prod-sa-get-rg-info-tpPqGO"