## Please do not touch this location 
s3_bucket       = "czr-platform-usw2-tf-state"
account         = "741762191802"
environment     = "dev"
s3_region       = "us-west-2"
s3_folder       = "share_tools"
s3_folder_type  = "iam"
s3_tfstate_file = "raas_iam.tfstate"
## Please do not touch above code 
region          = "us-west-2"

##roles and policies
existing_eks_cluster_role  = "czr-raas-eks-usw2-dev-rewards-app-node-role"
eks_cluster_policy         = "czr-raas-policy-dev-ekscluster-rewards-secret-manager"

##Secrets Information
jwt_secret              = "czr-raas-secret-usw2-dev-jwt-keys-wgKQBD"
database_secret         = "czr-raas-secret-usw2-dev-db-config-FqdgV4"
database_secret_raas_offers = "czr-raas-offers-secret-usw2-dev-db-config-2YlUDp"
strikeiron_secret       = "czr-raas-secret-usw2-dev-strikeiron-config-TgDiHD"
em1_secret              = "czr-raas-secret-usw2-dev-eml-keys-DeodTC"
gms_secret              = "czr-raas-secret-usw2-dev-gms-key-3VtVs0"
gms_guest_secret        = "czr-raas-secret-usw2-dev-gms-create-guest-key-ywAyP1"
pdb_republish_secret    = "czr-raas-secret-usw2-dev-pdb-republish-25eZQW"
kafka_secret            = "czr-raas-secret-usw2-dev-kafka-config-lTesCs"
security_questions_limit= "czr-raas-secret-usw2-dev-security-questions-limit-MVqLYs"
lambda_enc_secret       = "czr-raas-secret-usw2-dev-aws-lambda-enc-secret-TgDiHD"
gms_get_rg_secret       = "czr-raas-secret-usw2-dev-gms-get-rg-info-GJK3DT"
sms_secret              = "czr-raas-secret-usw2-dev-sms-service-config-uJNN6U"
error_logger_secret     = "czr-raas-secret-usw2-dev-caesars-error-logger-pE7wEG"
iden_encrypt_secret     = "czr-raas-secret-usw2-dev-iden-encrypt-secret-3eJK50"
tenable_audit           = "/svc/credentials/tenable-audit-1u5xfO"
crypto_Secret           = "cryptoSecret-zVJX6P"
jwt_config              = "jwt_config-6a5Yjy"
ENC_KEY                 = "ENC_KEY-SXaSHg"
GMS_KEYS                = "GMS_KEYS-WiVQkl"
oauthtoken              = "czr-raas-secret-usw2-dev-gms-validate-oauthtoken-key-Jx7F8X"
STRIKEIRON_CREDENTIAL   = "STRIKEIRON_CREDENTIAL-yjebZe"
role_name_flowlog       = "czr-raas-role-dev-flowlog"
policy_name_flowlog     = "czr-raas-policy-dev-flowlog"
leap_auth_provider_keys = "czr-raas-secret-usw2-dev-leap-auth-provider-keys-e0uf2o"
sa_get_rg_secret        = "czr-raas-secret-usw2-dev-sa-get-rg-info-7UGIlx"